name: elm_task
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  go_router: ^13.2.2
  flutter_bloc: ^8.1.3
  get_storage: ^2.1.1
  get_it: ^7.6.6
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.1.1
  slang: ^3.29.0
  slang_flutter: ^3.29.0
  internet_connection_checker: ^3.0.1
  intl: ^0.20.1
  flutter_screenutil: ^5.9.3
  dartz: ^0.10.1
  dio: ^5.7.0
  fl_chart: ^0.70.2
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.3
  logger: ^2.5.0
  # HTTP Inspector tool for Flutter which helps debugging http requests.
  requests_inspector: ^4.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/loading.gif
