import 'package:h_food/export.dart';
import 'package:google_fonts/google_fonts.dart';

final lightTextTheme = Typography.material2021().black.copyWith(
      displayLarge: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 40,
          fontWeight: FontWeight.bold,
          color: Colors.black),
      displayMedium: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 36,
          fontWeight: FontWeight.bold,
          color: Colors.black87),
      displaySmall: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 32,
          fontWeight: FontWeight.w500,
          color: Colors.black87),
      headlineLarge: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 28,
          fontWeight: FontWeight.bold,
          color: Colors.black),
      headlineMedium: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 24,
          fontWeight: FontWeight.w400,
          color: Colors.black87),
      headlineSmall: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 20,
          fontWeight: FontWeight.w500,
          color: Colors.black),
      titleLarge: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 18,
          fontWeight: FontWeight.w400,
          color: Colors.black),
      titleMedium: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 16,
          fontWeight: FontWeight.w500,
          color: Colors.black),
      titleSmall: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 14,
          fontWeight: FontWeight.w400,
          color: Colors.black54),
      bodyLarge: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 16,
          fontWeight: FontWeight.w400,
          color: Colors.black87),
      bodyMedium: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 14,
          fontWeight: FontWeight.w400,
          color: Colors.black87),
      bodySmall: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 12,
          fontWeight: FontWeight.w400,
          color: Colors.black54),
      labelLarge: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 14,
          fontWeight: FontWeight.w500,
          color: Colors.black87),
      labelMedium: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 12,
          fontWeight: FontWeight.w500,
          color: Colors.black54),
      labelSmall: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 10,
          fontWeight: FontWeight.w400,
          color: Colors.black45),
    );

final TextTheme darkTextTheme = Typography.material2021().white.copyWith(
      displayLarge: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 40,
          fontWeight: FontWeight.bold,
          color: Colors.white),
      displayMedium: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 36,
          fontWeight: FontWeight.bold,
          color: Colors.white70),
      displaySmall: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 32,
          fontWeight: FontWeight.w500,
          color: Colors.white70),
      headlineLarge: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 28,
          fontWeight: FontWeight.bold,
          color: Colors.white),
      headlineMedium: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 24,
          fontWeight: FontWeight.w400,
          color: Colors.white),
      headlineSmall: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 20,
          fontWeight: FontWeight.w400,
          color: Colors.white),
      titleLarge: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 18,
          fontWeight: FontWeight.w400,
          color: Colors.white),
      titleMedium: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 16,
          fontWeight: FontWeight.w500,
          color: Colors.white70),
      titleSmall: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 14,
          fontWeight: FontWeight.w400,
          color: Colors.white54),
      bodyLarge: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 16,
          fontWeight: FontWeight.w400,
          color: Colors.white70),
      bodyMedium: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 14,
          fontWeight: FontWeight.w400,
          color: Colors.white70),
      bodySmall: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 12,
          fontWeight: FontWeight.w400,
          color: Colors.white54),
      labelLarge: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 14,
          fontWeight: FontWeight.w600,
          color: Colors.white70),
      labelMedium: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 12,
          fontWeight: FontWeight.w500,
          color: Colors.white54),
      labelSmall: TextStyle(
          fontFamily: GoogleFonts.poppins().fontFamily,
          fontSize: 10,
          fontWeight: FontWeight.w400,
          color: Colors.white),
    );
